[package]
name = "scale_fixtures"
version = "0.1.0"
edition = "2021"

[lib]
path = "fixtures.rs"

[dependencies]
itertools = "0.10.3"
parity-scale-codec = { version = "3.0.0", features = ["derive"] }
