[package]
name = "scale_fixtures"
version = "0.1.0"
edition = "2021"

[lib]
path = "fixtures.rs"

[dependencies]
bitvec = "1.0.1"
itertools = "0.10.3"
parity-scale-codec = { version = "3.1.5", features = ["derive", "bit-vec"] }
primitive-types = "0.11.1"
